[2025-01-06 17:34:04 +1100] [2494066] [INFO] Starting gunicorn 23.0.0
[2025-01-06 17:34:04 +1100] [2494066] [INFO] Listening at: http://0.0.0.0:5004 (2494066)
[2025-01-06 17:34:04 +1100] [2494066] [INFO] Using worker: sync
[2025-01-06 17:34:04 +1100] [2494068] [INFO] Booting worker with pid: 2494068
[2025-01-06 17:34:04 +1100] [2494069] [INFO] Booting worker with pid: 2494069
[2025-01-06 17:34:05 +1100] [2494070] [INFO] Booting worker with pid: 2494070
[2025-01-06 17:34:05 +1100] [2494068] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/srv/apps/dvds/wsgi.py", line 1, in <module>
    from dvd_catalog_web.py import app
ModuleNotFoundError: No module named 'dvd_catalog_web.py'; 'dvd_catalog_web' is not a package
[2025-01-06 17:34:05 +1100] [2494068] [INFO] Worker exiting (pid: 2494068)
[2025-01-06 17:34:05 +1100] [2494069] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/srv/apps/dvds/wsgi.py", line 1, in <module>
    from dvd_catalog_web.py import app
ModuleNotFoundError: No module named 'dvd_catalog_web.py'; 'dvd_catalog_web' is not a package
[2025-01-06 17:34:05 +1100] [2494069] [INFO] Worker exiting (pid: 2494069)
[2025-01-06 17:34:05 +1100] [2494070] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/srv/apps/dvds/wsgi.py", line 1, in <module>
    from dvd_catalog_web.py import app
ModuleNotFoundError: No module named 'dvd_catalog_web.py'; 'dvd_catalog_web' is not a package
[2025-01-06 17:34:05 +1100] [2494070] [INFO] Worker exiting (pid: 2494070)
[2025-01-06 17:34:05 +1100] [2494066] [ERROR] Worker (pid:2494068) exited with code 3
[2025-01-06 17:34:05 +1100] [2494066] [ERROR] Worker (pid:2494070) was sent SIGTERM!
[2025-01-06 17:34:05 +1100] [2494066] [ERROR] Worker (pid:2494069) was sent SIGTERM!
[2025-01-06 17:34:05 +1100] [2494066] [ERROR] Shutting down: Master
[2025-01-06 17:34:05 +1100] [2494066] [ERROR] Reason: Worker failed to boot.
[2025-01-06 17:36:10 +1100] [2494423] [INFO] Starting gunicorn 23.0.0
[2025-01-06 17:36:10 +1100] [2494423] [INFO] Listening at: http://0.0.0.0:5004 (2494423)
[2025-01-06 17:36:10 +1100] [2494423] [INFO] Using worker: sync
[2025-01-06 17:36:10 +1100] [2494424] [INFO] Booting worker with pid: 2494424
[2025-01-06 17:36:10 +1100] [2494425] [INFO] Booting worker with pid: 2494425
[2025-01-06 17:36:10 +1100] [2494426] [INFO] Booting worker with pid: 2494426
[2025-01-06 18:07:01 +1100] [2494423] [INFO] Handling signal: term
[2025-01-06 18:07:01 +1100] [2494424] [INFO] Worker exiting (pid: 2494424)
[2025-01-06 18:07:01 +1100] [2494425] [INFO] Worker exiting (pid: 2494425)
[2025-01-06 18:07:01 +1100] [2494426] [INFO] Worker exiting (pid: 2494426)
[2025-01-06 18:07:01 +1100] [2494423] [ERROR] Worker (pid:2494424) was sent SIGTERM!
[2025-01-06 18:07:01 +1100] [2494423] [ERROR] Worker (pid:2494426) was sent SIGTERM!
[2025-01-06 18:07:01 +1100] [2494423] [ERROR] Worker (pid:2494425) was sent SIGTERM!
[2025-01-06 18:07:02 +1100] [2494423] [INFO] Shutting down: Master
[2025-01-06 18:07:02 +1100] [2499781] [INFO] Starting gunicorn 23.0.0
[2025-01-06 18:07:02 +1100] [2499781] [INFO] Listening at: http://0.0.0.0:5004 (2499781)
[2025-01-06 18:07:02 +1100] [2499781] [INFO] Using worker: sync
[2025-01-06 18:07:02 +1100] [2499787] [INFO] Booting worker with pid: 2499787
[2025-01-06 18:07:02 +1100] [2499788] [INFO] Booting worker with pid: 2499788
[2025-01-06 18:07:02 +1100] [2499789] [INFO] Booting worker with pid: 2499789
[2025-01-06 18:13:04 +1100] [2499781] [INFO] Handling signal: term
[2025-01-06 18:13:04 +1100] [2499787] [INFO] Worker exiting (pid: 2499787)
[2025-01-06 18:13:04 +1100] [2499789] [INFO] Worker exiting (pid: 2499789)
[2025-01-06 18:13:04 +1100] [2499788] [INFO] Worker exiting (pid: 2499788)
[2025-01-06 18:13:04 +1100] [2499781] [INFO] Shutting down: Master
[2025-01-06 18:13:04 +1100] [2500731] [INFO] Starting gunicorn 23.0.0
[2025-01-06 18:13:04 +1100] [2500731] [INFO] Listening at: http://0.0.0.0:5004 (2500731)
[2025-01-06 18:13:04 +1100] [2500731] [INFO] Using worker: sync
[2025-01-06 18:13:04 +1100] [2500732] [INFO] Booting worker with pid: 2500732
[2025-01-06 18:13:04 +1100] [2500733] [INFO] Booting worker with pid: 2500733
[2025-01-06 18:13:04 +1100] [2500734] [INFO] Booting worker with pid: 2500734
[2025-01-06 18:13:49,442] ERROR in app: Exception on /add [POST]
Traceback (most recent call last):
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/srv/apps/dvds/dvd_catalog_web.py", line 41, in add_dvd
    return redirect(url_for('/dvds/add'))
                    ~~~~~~~^^^^^^^^^^^^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint '/dvds/add'. Did you mean 'add_dvd' instead?
[2025-01-06 18:18:12 +1100] [2500731] [INFO] Handling signal: term
[2025-01-06 18:18:12 +1100] [2500732] [INFO] Worker exiting (pid: 2500732)
[2025-01-06 18:18:12 +1100] [2500733] [INFO] Worker exiting (pid: 2500733)
[2025-01-06 18:18:12 +1100] [2500734] [INFO] Worker exiting (pid: 2500734)
[2025-01-06 18:18:12 +1100] [2500731] [INFO] Shutting down: Master
[2025-01-06 18:18:12 +1100] [2502335] [INFO] Starting gunicorn 23.0.0
[2025-01-06 18:18:12 +1100] [2502335] [INFO] Listening at: http://0.0.0.0:5004 (2502335)
[2025-01-06 18:18:12 +1100] [2502335] [INFO] Using worker: sync
[2025-01-06 18:18:12 +1100] [2502338] [INFO] Booting worker with pid: 2502338
[2025-01-06 18:18:12 +1100] [2502339] [INFO] Booting worker with pid: 2502339
[2025-01-06 18:18:12 +1100] [2502340] [INFO] Booting worker with pid: 2502340
[2025-01-06 18:19:36,031] ERROR in app: Exception on /add [POST]
Traceback (most recent call last):
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/srv/apps/dvds/dvd_catalog_web.py", line 41, in add_dvd
    return redirect(url_for('/dvds/all'))
                    ~~~~~~~^^^^^^^^^^^^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/smatthews_a/miniconda3/envs/mod_dep/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint '/dvds/all'. Did you mean 'add_dvd' instead?
[2025-01-06 18:22:05 +1100] [2502335] [INFO] Handling signal: term
[2025-01-06 18:22:05 +1100] [2502338] [INFO] Worker exiting (pid: 2502338)
[2025-01-06 18:22:05 +1100] [2502340] [INFO] Worker exiting (pid: 2502340)
[2025-01-06 18:22:05 +1100] [2502339] [INFO] Worker exiting (pid: 2502339)
[2025-01-06 18:22:05 +1100] [2502335] [ERROR] Worker (pid:2502340) was sent SIGTERM!
[2025-01-06 18:22:05 +1100] [2502335] [ERROR] Worker (pid:2502339) was sent SIGTERM!
[2025-01-06 18:22:05 +1100] [2502335] [ERROR] Worker (pid:2502338) was sent SIGTERM!
[2025-01-06 18:22:05 +1100] [2502335] [INFO] Shutting down: Master
[2025-01-06 18:22:05 +1100] [2503105] [INFO] Starting gunicorn 23.0.0
[2025-01-06 18:22:05 +1100] [2503105] [INFO] Listening at: http://0.0.0.0:5004 (2503105)
[2025-01-06 18:22:05 +1100] [2503105] [INFO] Using worker: sync
[2025-01-06 18:22:05 +1100] [2503106] [INFO] Booting worker with pid: 2503106
[2025-01-06 18:22:05 +1100] [2503107] [INFO] Booting worker with pid: 2503107
[2025-01-06 18:22:05 +1100] [2503108] [INFO] Booting worker with pid: 2503108
[2025-01-16 21:20:38 +1100] [2503107] [INFO] Worker exiting (pid: 2503107)
[2025-01-16 21:20:38 +1100] [2503106] [INFO] Worker exiting (pid: 2503106)
[2025-01-16 21:20:38 +1100] [2503105] [INFO] Handling signal: term
[2025-01-16 21:20:39 +1100] [2503108] [INFO] Worker exiting (pid: 2503108)
[2025-01-16 21:20:41 +1100] [2503105] [ERROR] Worker (pid:2503106) was sent SIGTERM!
[2025-01-16 21:20:41 +1100] [2503105] [ERROR] Worker (pid:2503107) was sent SIGTERM!
[2025-01-16 21:20:55 +1100] [2503105] [INFO] Shutting down: Master
[2025-01-16 21:21:40 +1100] [1191] [INFO] Starting gunicorn 23.0.0
[2025-01-16 21:21:40 +1100] [1191] [INFO] Listening at: http://0.0.0.0:5004 (1191)
[2025-01-16 21:21:40 +1100] [1191] [INFO] Using worker: sync
[2025-01-16 21:21:40 +1100] [1633] [INFO] Booting worker with pid: 1633
[2025-01-16 21:21:40 +1100] [1641] [INFO] Booting worker with pid: 1641
[2025-01-16 21:21:40 +1100] [1653] [INFO] Booting worker with pid: 1653
[2025-02-13 20:22:48 +1100] [1191] [INFO] Handling signal: term
[2025-02-13 20:22:48 +1100] [1653] [INFO] Worker exiting (pid: 1653)
[2025-02-13 20:22:48 +1100] [1633] [INFO] Worker exiting (pid: 1633)
[2025-02-13 20:22:48 +1100] [1641] [INFO] Worker exiting (pid: 1641)
[2025-02-13 20:23:12 +1100] [1191] [INFO] Shutting down: Master
[2025-02-13 20:23:50 +1100] [1203] [INFO] Starting gunicorn 23.0.0
[2025-02-13 20:23:50 +1100] [1203] [INFO] Listening at: http://0.0.0.0:5004 (1203)
[2025-02-13 20:23:50 +1100] [1203] [INFO] Using worker: sync
[2025-02-13 20:23:50 +1100] [1651] [INFO] Booting worker with pid: 1651
[2025-02-13 20:23:50 +1100] [1685] [INFO] Booting worker with pid: 1685
[2025-02-13 20:23:50 +1100] [1696] [INFO] Booting worker with pid: 1696
[2025-02-22 08:58:10 +1100] [1203] [INFO] Handling signal: term
[2025-02-22 08:58:10 +1100] [1651] [INFO] Worker exiting (pid: 1651)
[2025-02-22 08:58:10 +1100] [1685] [INFO] Worker exiting (pid: 1685)
[2025-02-22 08:58:10 +1100] [1696] [INFO] Worker exiting (pid: 1696)
[2025-02-22 08:58:29 +1100] [1203] [INFO] Shutting down: Master
[2025-02-22 08:59:12 +1100] [1200] [INFO] Starting gunicorn 23.0.0
[2025-02-22 08:59:12 +1100] [1200] [INFO] Listening at: http://0.0.0.0:5004 (1200)
[2025-02-22 08:59:12 +1100] [1200] [INFO] Using worker: sync
[2025-02-22 08:59:12 +1100] [1662] [INFO] Booting worker with pid: 1662
[2025-02-22 08:59:12 +1100] [1670] [INFO] Booting worker with pid: 1670
[2025-02-22 08:59:12 +1100] [1693] [INFO] Booting worker with pid: 1693
[2025-03-13 20:26:55 +1100] [1200] [INFO] Handling signal: term
[2025-03-13 20:26:55 +1100] [1662] [INFO] Worker exiting (pid: 1662)
[2025-03-13 20:26:55 +1100] [1693] [INFO] Worker exiting (pid: 1693)
[2025-03-13 20:26:55 +1100] [1670] [INFO] Worker exiting (pid: 1670)
[2025-03-13 20:27:18 +1100] [1200] [INFO] Shutting down: Master
[2025-03-13 20:27:57 +1100] [1186] [INFO] Starting gunicorn 23.0.0
[2025-03-13 20:27:57 +1100] [1186] [INFO] Listening at: http://0.0.0.0:5004 (1186)
[2025-03-13 20:27:57 +1100] [1186] [INFO] Using worker: sync
[2025-03-13 20:27:57 +1100] [1710] [INFO] Booting worker with pid: 1710
[2025-03-13 20:27:57 +1100] [1737] [INFO] Booting worker with pid: 1737
[2025-03-13 20:27:57 +1100] [1728] [INFO] Booting worker with pid: 1728
[2025-04-17 19:47:49 +1000] [1186] [INFO] Handling signal: term
[2025-04-17 19:47:49 +1000] [1710] [INFO] Worker exiting (pid: 1710)
[2025-04-17 19:47:49 +1000] [1728] [INFO] Worker exiting (pid: 1728)
[2025-04-17 19:47:50 +1000] [1737] [INFO] Worker exiting (pid: 1737)
[2025-04-17 19:48:07 +1000] [1186] [INFO] Shutting down: Master
[2025-04-17 20:48:49 +1000] [1193] [INFO] Starting gunicorn 23.0.0
[2025-04-17 20:48:49 +1000] [1193] [INFO] Listening at: http://0.0.0.0:5004 (1193)
[2025-04-17 20:48:49 +1000] [1193] [INFO] Using worker: sync
[2025-04-17 20:48:49 +1000] [1689] [INFO] Booting worker with pid: 1689
[2025-04-17 20:48:49 +1000] [1702] [INFO] Booting worker with pid: 1702
[2025-04-17 20:48:49 +1000] [1723] [INFO] Booting worker with pid: 1723
[2025-05-15 20:15:33 +1000] [1193] [INFO] Handling signal: term
[2025-05-15 20:15:34 +1000] [1702] [INFO] Worker exiting (pid: 1702)
[2025-05-15 20:15:34 +1000] [1723] [INFO] Worker exiting (pid: 1723)
[2025-05-15 20:15:34 +1000] [1689] [INFO] Worker exiting (pid: 1689)
[2025-05-15 20:15:54 +1000] [1193] [INFO] Shutting down: Master
[2025-05-15 20:16:31 +1000] [1203] [INFO] Starting gunicorn 23.0.0
[2025-05-15 20:16:31 +1000] [1203] [INFO] Listening at: http://0.0.0.0:5004 (1203)
[2025-05-15 20:16:31 +1000] [1203] [INFO] Using worker: sync
[2025-05-15 20:16:31 +1000] [1712] [INFO] Booting worker with pid: 1712
[2025-05-15 20:16:31 +1000] [1705] [INFO] Booting worker with pid: 1705
[2025-05-15 20:16:31 +1000] [1719] [INFO] Booting worker with pid: 1719
[2025-06-19 20:47:13 +1000] [1203] [INFO] Handling signal: term
[2025-06-19 20:47:13 +1000] [1719] [INFO] Worker exiting (pid: 1719)
[2025-06-19 20:47:13 +1000] [1705] [INFO] Worker exiting (pid: 1705)
[2025-06-19 20:47:13 +1000] [1712] [INFO] Worker exiting (pid: 1712)
[2025-06-19 20:47:31 +1000] [1203] [INFO] Shutting down: Master
[2025-06-19 20:49:42 +1000] [1198] [INFO] Starting gunicorn 23.0.0
[2025-06-19 20:49:42 +1000] [1198] [INFO] Listening at: http://0.0.0.0:5004 (1198)
[2025-06-19 20:49:42 +1000] [1198] [INFO] Using worker: sync
[2025-06-19 20:49:42 +1000] [1671] [INFO] Booting worker with pid: 1671
[2025-06-19 20:49:42 +1000] [1692] [INFO] Booting worker with pid: 1692
[2025-06-19 20:49:42 +1000] [1702] [INFO] Booting worker with pid: 1702
[2025-07-17 19:49:29 +1000] [1198] [INFO] Handling signal: term
[2025-07-17 19:49:29 +1000] [1671] [INFO] Worker exiting (pid: 1671)
[2025-07-17 19:49:29 +1000] [1692] [INFO] Worker exiting (pid: 1692)
[2025-07-17 19:49:29 +1000] [1702] [INFO] Worker exiting (pid: 1702)
[2025-07-17 19:49:50 +1000] [1198] [INFO] Shutting down: Master
[2025-07-17 19:50:28 +1000] [1211] [INFO] Starting gunicorn 23.0.0
[2025-07-17 19:50:28 +1000] [1211] [INFO] Listening at: http://0.0.0.0:5004 (1211)
[2025-07-17 19:50:28 +1000] [1211] [INFO] Using worker: sync
[2025-07-17 19:50:28 +1000] [1682] [INFO] Booting worker with pid: 1682
[2025-07-17 19:50:28 +1000] [1711] [INFO] Booting worker with pid: 1711
[2025-07-17 19:50:28 +1000] [1722] [INFO] Booting worker with pid: 1722
[2025-07-26 10:45:31 +1000] [1211] [INFO] Handling signal: term
[2025-07-26 10:45:31 +1000] [1722] [INFO] Worker exiting (pid: 1722)
[2025-07-26 10:45:31 +1000] [1711] [INFO] Worker exiting (pid: 1711)
[2025-07-26 10:45:31 +1000] [1682] [INFO] Worker exiting (pid: 1682)
[2025-07-26 10:45:48 +1000] [1211] [INFO] Shutting down: Master
[2025-07-26 10:46:27 +1000] [1224] [INFO] Starting gunicorn 23.0.0
[2025-07-26 10:46:27 +1000] [1224] [INFO] Listening at: http://0.0.0.0:5004 (1224)
[2025-07-26 10:46:27 +1000] [1224] [INFO] Using worker: sync
[2025-07-26 10:46:27 +1000] [1766] [INFO] Booting worker with pid: 1766
[2025-07-26 10:46:28 +1000] [1782] [INFO] Booting worker with pid: 1782
[2025-07-26 10:46:28 +1000] [1778] [INFO] Booting worker with pid: 1778
